language: node_js
node_js:
  - "lts/*"
cache:
  directories:
    - node_modules
scripts:
  - npm test
  - npm run build:example
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: examples/dist
  on:
    branch: master
